### ISSUE TITLE
怎么没有斜体

### ISSUE THREAD

**Issue by JinJieGu** [iwgang/SimplifySpan#3]

**Comment by JinJieGu** [comment]
@iwgang 不错的库，我作了字体支持，具体更改请看[https://github.com/iwgang/SimplifySpan/pull/4](https://github.com/iwgang/SimplifySpan/pull/4)，你运行下如果没问题，就merge下。

**Comment by iwgang** [comment]
@JinJieGu 感谢提pr，我这两天整理一下后 merge 然后发布个新版本

**Comment by iwgang** [comment]
fix v2.1
