### ISSUE TITLE
动态更新显示问题

### ISSUE THREAD

**Issue by wzgiceman** [iwgang/SimplifySpan#5]
你好,请问在这个库上面如果添加动态刷新的功能,比如播放歌曲或者阅读器的时候需要文字实时同步高亮这种需求?

**Comment by iwgang** [comment]
该库的作用就是便捷产生 Spannable 而已，所以如果需要做动态，那么就需要重新再产生新的 Spannable 设置到 TextView 中去

**Comment by wzgiceman** [comment]
了解,thx
